ENH: moved partial specializations to cpp file because of:
CMakeFiles/ImageCompleter.dir/src/image-completer-cmd/CommandLineOptions.cpp.o: In function `Tech::CmdLine::ParamOption<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::ReadOption(char const*)':
/home/doriad/src/wxWidgets-2.9.1/include/wx/buffer.h:44: multiple definition of `Tech::CmdLine::ParamOption<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::ReadOption(char const*)'
CMakeFiles/ImageCompleter.dir/src/image-completer-cmd/Main.cpp.o:/media/portable/Projects/src/lafarren-image-completer/src/tech/tech/CmdLine.inl:37: first defined here
CMakeFiles/ImageCompleter.dir/src/image-completer-cmd/CommandLineOptions.cpp.o: In function `Tech::CmdLine::ParamOption<int>::ReadOption(char const*)':